"""Reproduce the person-clustered external-validity models reported in Table 6.

Inputs are generated by R/12_export_extvalid.R and are not distributed because they
contain participant-level cohort observations.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf


REFERENCE = {
    ("HRS CIDI-SF", "raw"): (-0.210, -0.260, -0.160),
    ("HRS CIDI-SF", "corrected"): (-0.227, -0.294, -0.160),
    ("ELSA handgrip", "raw"): (0.661, 0.357, 0.965),
    ("ELSA handgrip", "corrected"): (0.613, 0.329, 0.897),
}


def zscore(series: pd.Series) -> pd.Series:
    """Sample-standardize a score, matching R's scale() default (ddof=1)."""
    return (series - series.mean()) / series.std(ddof=1)


def validate_columns(data: pd.DataFrame, required: set[str], source: Path) -> None:
    missing = sorted(required.difference(data.columns))
    if missing:
        raise ValueError(f"{source} is missing required columns: {', '.join(missing)}")


def interaction_row(model, term: str, analysis: str, score: str, data: pd.DataFrame) -> dict:
    confidence = model.conf_int().loc[term]
    return {
        "analysis": analysis,
        "score": score,
        "observations": int(model.nobs),
        "persons": int(data["id"].nunique()),
        "interaction": float(model.params[term]),
        "ci_lower": float(confidence.iloc[0]),
        "ci_upper": float(confidence.iloc[1]),
        "p_value": float(model.pvalues[term]),
    }


def fit_hrs(path: Path) -> list[dict]:
    data = pd.read_csv(path)
    validate_columns(
        data,
        {"id", "wave", "female", "cesd", "corr", "cidi_mde3"},
        path,
    )
    data = data.dropna(subset=["id", "female", "cesd", "corr", "cidi_mde3"]).copy()
    data["raw"] = zscore(data["cesd"])
    data["corrected"] = zscore(data["corr"])
    rows = []
    for score in ("raw", "corrected"):
        model = smf.glm(
            f"cidi_mde3 ~ {score} * female",
            data=data,
            family=sm.families.Binomial(),
        ).fit(cov_type="cluster", cov_kwds={"groups": data["id"]})
        rows.append(
            interaction_row(
                model,
                f"{score}:female",
                "HRS CIDI-SF",
                score,
                data,
            )
        )
    return rows


def fit_elsa(path: Path) -> list[dict]:
    data = pd.read_csv(path)
    validate_columns(
        data,
        {"id", "wave", "female", "agey", "cesd", "corr", "grip_max"},
        path,
    )
    data = data.dropna(
        subset=["id", "female", "agey", "cesd", "corr", "grip_max"]
    ).copy()
    data["raw"] = zscore(data["cesd"])
    data["corrected"] = zscore(data["corr"])
    rows = []
    for score in ("raw", "corrected"):
        model = smf.ols(
            f"grip_max ~ {score} * female + agey",
            data=data,
        ).fit(cov_type="cluster", cov_kwds={"groups": data["id"]})
        rows.append(
            interaction_row(
                model,
                f"{score}:female",
                "ELSA handgrip",
                score,
                data,
            )
        )
    return rows


def check_reference(results: pd.DataFrame, tolerance: float = 0.002) -> None:
    for row in results.to_dict("records"):
        expected = REFERENCE[(row["analysis"], row["score"])]
        observed = (row["interaction"], row["ci_lower"], row["ci_upper"])
        if any(abs(value - target) > tolerance for value, target in zip(observed, expected)):
            raise RuntimeError(
                f"Published-value check failed for {row['analysis']} ({row['score']}): "
                f"observed={observed}, expected={expected}"
            )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path("export"),
        help="Directory containing export_hrs_cidi.csv and export_elsa_grip.csv",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("output/clustered_external_validity.csv"),
        help="Summary CSV to write",
    )
    parser.add_argument(
        "--check-published",
        action="store_true",
        help="Fail unless rounded coefficients and 95%% CIs match the manuscript values",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    results = pd.DataFrame(
        fit_hrs(args.input_dir / "export_hrs_cidi.csv")
        + fit_elsa(args.input_dir / "export_elsa_grip.csv")
    )
    if args.check_published:
        check_reference(results)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    results.to_csv(args.output, index=False)
    print(results.to_string(index=False, float_format=lambda value: f"{value:.6g}"))
    print(f"\nWrote {args.output}")


if __name__ == "__main__":
    main()
